### ISSUE TITLE
puppeteer.chromium_downloader connection fail

### ISSUE THREAD

**Issue by anamariatp** [betatim/notebook-as-pdf#11]
Hi there,

I installed the package but the chromium downloader fails or gets stuck (I am using a Windows server behind a proxy).

Any thoughts on workarounds that I can try? I have Chromium installed already.

Thanks!
Ana

**Comment by betatim** [comment]
Not really unfortunately. You could try running `pyppeteer-install` in a terminal to manually run the download&setup step. Maybe that is easier to retry or is smarter about using the proxy settings.

Beyond that I'd ask in the pyppeteer GitHub repository about advice on how to get it installed when behind a proxy.
