### ISSUE TITLE
Custom page height?

### ISSUE THREAD

**Issue by astronomyk** [betatim/notebook-as-pdf#28]
Hi!

Thanks for the package, I've so far found it very useful for several projects!

Alas I currently have the problem that I need to deliver some notebooks as PDFs but client requires there to be A4-size page breaks.
I quickly found [this line, which I assume controls when a page break is inserted](https://github.com/betatim/notebook-as-pdf/blob/362f2c6ed9693a43b8c5f38dc89efc89965ae06d/notebook_as_pdf/__init__.py#L98) (i.e. for the 200 inch Adobe limit).

I've cloned the repo, changed height to 11.7 * 72 (for A4 standard) and reinstalled the package from my local copy. Unfortunately I still only get single page PDFs.
Is this the right place to be changing the page height limit? Or should I look somewhere else?

Many thanks for your time!
Kieran

(P.S. my deadline is Sunday 11th of April, so any help before then would be greatly appreciated. Thanks!!)

**Comment by betatim** [comment]
Yes that is the place where we set the height/control the page size. Without seeing your code I have no good idea why setting it doesn't work :-/

**Comment by astronomyk** [comment]
Thanks again for fixing the nbconvert 6+ issue. Everything works as expected now, so this issue is obsolete. 

P.S. I appreciate the sentiment regarding having a continuous page for notebooks (I prefer it too), but it might be useful for others in the future to have the option of setting their own page length limits. Cheers!
