### ISSUE TITLE
Python 3.6 not supported

### ISSUE THREAD

**Issue by LiuChuang0059** [betatim/notebook-as-pdf#3]
when i run it , i get an error 

nbconvert failed: module 'asyncio' has no attribute 'run'

Python 3.6 doesn't have this function

**Comment by LiuChuang0059** [comment]
when i run it , i get an error 

nbconvert failed: module 'asyncio' has no attribute 'run'

Python 3.6 doesn't have this function

**Comment by betatim** [comment]
That is correct. I will update the requirement to 3.7

**Comment by betatim** [comment]
I updated `setup.py` to show that Python 3.7 is required.
