### ISSUE TITLE
nbconvert failed: Navigation Timeout Exceeded: 30000 ms exceeded.

### ISSUE THREAD

**Issue by Lucaslpena** [betatim/notebook-as-pdf#30]
I am currently running the `File > "Download as" > "PDf via puppeteer (.html)` and getting the following error:

```
500 : Internal Server Error
nbconvert failed: Navigation Timeout Exceeded: 30000 ms exceeded.
```

How can I edit the length of this timeout while still using this "Download as PDF" approach?

**Comment by betatim** [comment]
The "PDF via puppeteer" option isn't using notebook-as-pdf. You need to ask your question in the nbconvert issue tracker instead.
