### ISSUE TITLE
Fails when run as root

### ISSUE THREAD

**Issue by ian-r-rose** [betatim/notebook-as-pdf#7]
Thanks for this! As much as I like LaTeX on occasion, it's nice to have another option.

I have found that this exporter fails when run as root due to Chrome sandboxing policies. Might we add an option to turn off sandboxing?

cf. https://github.com/ian-r-rose/notebook-as-pdf/commit/9d9249046ae0725faa510ac9280d9b2041c3d72a

**Comment by betatim** [comment]
Sounds like a good idea. Do you understand/know what the sandbox does/is good for? What bad (or good) things happen when you turn it off?

**Comment by ian-r-rose** [comment]
To be honest, I haven't really done my homework here yet. I'm sure it's there for good reasons, but I ran into a case where I didn't really have a choice.

I'll do a bit of research and report back.

**Comment by betatim** [comment]
Feel free to open a PR already. If we can't (quickly) figure out what bad stuff will happen then maybe it can't be that bad?? Maybe?

**Comment by ian-r-rose** [comment]
So, the sandboxing (as the name suggests) is intended to prevent [untrusted code](https://developers.google.com/web/tools/puppeteer/troubleshooting#setting_up_chrome_linux_sandbox) from being executed on the system. The universe of bad stuff that could happen in that case is pretty large.

Apparently sandboxing cannot work if you run as root. So in order to do this, you have to explicitly disable sandboxing.
The more recommended way to proceed is to create a new user (as is done in the juptyer stacks, as well as the [example dockerfile](https://developers.google.com/web/tools/puppeteer/troubleshooting#running_puppeteer_in_docker) in the puppeteer docs.

In my particular case, I am somewhat constrained in needing to be root, so it would still be useful to expose the option, even if it is mostly a bad idea.
